// Copyright 2025 JesusTouchMe

#ifndef BIBBLE_TEMPLATES_HEADERSTART_H
#define BIBBLE_TEMPLATES_HEADERSTART_H 1

namespace templates {
    constexpr const char* HeaderStart = R"(/* This header was generated by the Bibble compiler. DO NOT EDIT */

#ifndef _BIBBLE_GENERATED_{0}_H
#define _BIBBLE_GENERATED_{0}_H

#include "JesusVM/JesusNative.h"

#ifdef __cplusplus
extern "C" {{
#endif

)";
}

#endif // BIBBLE_TEMPLATES_HEADERSTART_H
